name: fermipy-v1-0-1
channels:
  - fermi
  - conda-forge
dependencies:
  - python[version<'3.10']
  - pyyaml
  - numpy[version='>=1.16']
  - scipy
  - astropy
  - matplotlib
  - pandas
  - healpy
  - astropy-healpix
  - gammapy[version='>=0.18']
  - fermitools
  - clhep
  - ipython
  - jupyter
  - jupyterlab
  - libpng