name: fermipy-v1-2-2
channels:
  - fermi
  - conda-forge
dependencies:
  - python=3.9
  - pyyaml
  - numpy
  - scipy
  - astropy
  - matplotlib<3.9
  - pandas
  - healpy
  - astropy-healpix
  - gammapy>=0.18
  - fermitools=2.2.0
  - clhep
  - ipython
  - jupyter
  - jupyterlab
  - libpng
  - fermipy="v1.2"
  - ipykernel