name: fermipy-v1-2-2
channels:
  - fermi
  - conda-forge
dependencies:
  - python=3.9
  - pyyaml
  - numpy=1.20
  - scipy
  - astropy
  - matplotlib
  - pandas
  - healpy
  - astropy-healpix
  - gammapy>=0.18
  - fermitools
  - clhep
  - ipython
  - jupyter
  - jupyterlab
  - libpng